<a href="https://colab.research.google.com/github/123Prostab/Projects/blob/main/tensor_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
%matplotlib inline

Tensors are a specialized data structure that are very similar to arrays and matrices.
In PyTorch, we use tensors to encode the inputs and outputs of a model, as well as the model’s parameters.


In [5]:
import torch 
import numpy as np


Directly from data

In [6]:
data = [[1,2],[3,4]]
x_data = torch.tensor(data)

from numpy array

In [7]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

from another tensor

In [8]:
x_ones = torch.ones_like(x_data)# retain the property of x
print(f"One Tensor: \n{x_ones}")

One Tensor: 
tensor([[1, 1],
        [1, 1]])


In [9]:
x_rand = torch.rand_like(x_data,dtype = torch.float)
print(f"Random Tensor: \n {x_rand}\n")

Random Tensor: 
 tensor([[0.2188, 0.5513],
        [0.5555, 0.3100]])



with constant or random values

In [10]:
shape = (2,3)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

In [11]:
print(f"rand_tensor: \n{rand_tensor}")
print(f"Ones tensor:\n{ones_tensor}")
print(f"zeros_tensor : \n {zeros_tensor}")

rand_tensor: 
tensor([[0.2141, 0.2784, 0.0343],
        [0.5699, 0.4584, 0.3164]])
Ones tensor:
tensor([[1., 1., 1.],
        [1., 1., 1.]])
zeros_tensor : 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


# Attribute of tensor:
shape , data type , the device where they are stored

In [12]:
from torch._C import dtype
tensor = torch.rand(3,4)
print(f"Shape of the tensor:{tensor.shape}")
print(f"data type of tensor:{tensor.dtype}")
print(f"Device tensor is stored on:{tensor.device}")


Shape of the tensor:torch.Size([3, 4])
data type of tensor:torch.float32
Device tensor is stored on:cpu


Operation on tensor

In [13]:
if torch.cuda.is_available():
  tensor = tensor.to("cuda")

Standard numpy like indexing and slicing

In [14]:
tensor = torch.ones(4,4)
print(f"first row : {tensor[0]}")
print(f"first column :{tensor[:,0]}")
print(f"last column :{tensor[:,-1]}")
tensor[:,1] = 0
print(tensor)

first row : tensor([1., 1., 1., 1.])
first column :tensor([1., 1., 1., 1.])
last column :tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


joining tensor

In [15]:
t1 = torch.cat([tensor,tensor,tensor],dim = 1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


Arithmetic operation

In [22]:
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)
y3 = torch.rand_like(y1)
torch.matmul(tensor,tensor.T,out = y3)#y1, y2, y3 has same value

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

In [24]:
z1 = tensor * tensor
z2 = tensor.mul(tensor)
z3 = torch.rand_like(tensor)
torch.mul(tensor,tensor,out = z3)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

Single element tensors

In [25]:
agg = tensor.sum()
agg_item = agg.item()
print(agg_item,type(agg_item))

12.0 <class 'float'>


In [26]:
print(agg)

tensor(12.)


In Place opeartion

In [27]:
print(f"{tensor} \n")
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


Bridge with numpy

In [28]:
t = torch.ones(5)
print(f"t : {t}")
n = t.numpy()
print(f"n: {n}")

t : tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


A change in the tensor reflects in the numpy array

In [29]:
t.add_(1)
print(f"t : {t}")
print(f"n: {n}")

t : tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


Change in the numpy array reflects the tensor

In [30]:
np.add(n,1,out = n)
print(f"t : {t}")
print(f"n: {n}")

t : tensor([3., 3., 3., 3., 3.])
n: [3. 3. 3. 3. 3.]
